# Generated by Django 4.1.7 on 2023-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dekho", "0004_product_company_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
