# Generated by Django 4.1.7 on 2023-03-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekho', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20),
        ),
    ]
